###讀取csv

In [92]:
import pandas as pd
df = pd.read_csv('student.csv',index_col=0)  # 利用index_col=0 來指定第一個欄位作為索引
df

     chinese  english  math  geo  explore
魏秋萍       88       97    50   96       75
鄭孟芳       69       98    61   82       83
李彥伸       77       64    76   65       50
李湘婷       88       89    78   60       64
劉佳佩       80       81    65   59       86
簡國瑋       53       84    54   76       66
童建霖       69       95   100   56       70
陳筱涵       76       83    78  100       98
高智超       68       64    83   70       60
林益妏       72       52    79   80       61
黃柏宇       70       75    81   60       55
蔡至剛       83       69    57   86       76
林志成       57       53    71   93       82
羅幸娥       90       59    95   57       71
王梅劭       73       91    68   50       96
吳志宣       63      100    76   89       96
游倫城       83       56    57   56       53
周家銘       64       97    66   52       51
陳淑萍       98       81    79   68       83
錢佩豪       74       55    64   81       60
陳信宏       70       77    98   79       83
林淑安       88       62    84   68       71
劉慧君       61       88    95   69       76
林珈發       57      100    51   67       90
張家秀       64      100    85   67       59
柯宜臻       68       63    89   96       69
林瑞喬       71      100    61   82       84
林麗萍       81       69    73   80       56
李立偉       77       94    51   53       63
黃必琪       78       68    60   53       84
楊偉翔       73       96    98   94       65
陳奇瑄       96       81    50   67       86
李進慧       74       86    74   57       76
王雅琴       75       55    94   79       81
沈心利       98       94    87   82       92
鄧哲榮       59       55    54   72       50
游詩亞       51       73    91   86       78
蔡欣汝       89       54    80   77       77
黃靜怡       58       61    57   59       71
尚偉倫       92       86    57   76       70
葉祖雄       61       66    76   86       60
林俊翔       95       69    73   50       63
郭致恬       81       79    98   50       80
盧冠發       53       58    67   56       75
蔡士賢       80       77    51   84       57
楊健麟       96       98    89   77       66
柯韋成       51       83    61   60       79
李蓉瑞       79       82    55   82       73
王坤安       64       50    94   94       57
郎慧萍       64       71    54   71       64

###讀取excel

In [23]:
df = pd.read_excel('student.xlsx',index_col=0) 
df
df.head()

     chinese  english  math  geo  explore
魏秋萍       88       97    50   96       75
鄭孟芳       69       98    61   82       83
李彥伸       77       64    76   65       50
李湘婷       88       89    78   60       64
劉佳佩       80       81    65   59       86

###透過欄選取
###透過列選取

In [24]:
#透過欄選取
#單欄選取
df['chinese']  #一維資料--series

魏秋萍    88
鄭孟芳    69
李彥伸    77
李湘婷    88
劉佳佩    80
簡國瑋    53
童建霖    69
陳筱涵    76
高智超    68
林益妏    72
黃柏宇    70
蔡至剛    83
林志成    57
羅幸娥    90
王梅劭    73
吳志宣    63
游倫城    83
周家銘    64
陳淑萍    98
錢佩豪    74
陳信宏    70
林淑安    88
劉慧君    61
林珈發    57
張家秀    64
柯宜臻    68
林瑞喬    71
林麗萍    81
李立偉    77
黃必琪    78
楊偉翔    73
陳奇瑄    96
李進慧    74
王雅琴    75
沈心利    98
鄧哲榮    59
游詩亞    51
蔡欣汝    89
黃靜怡    58
尚偉倫    92
葉祖雄    61
林俊翔    95
郭致恬    81
盧冠發    53
蔡士賢    80
楊健麟    96
柯韋成    51
李蓉瑞    79
王坤安    64
郎慧萍    64
Name: chinese, dtype: int64

In [ ]:
#多欄選取
df[['chinese','math']]    #subscript--最外圍[]叫subscript

In [ ]:
#loc->使用索引的名稱
#iloc->使用索引的index

df.loc['王坤安']
df.loc[['王坤安','林俊翔']]  #裡面再放一個[]代表要選多個

     chinese  english  math  geo  explore
王坤安       64       50    94   94       57
林俊翔       95       69    73   50       63

In [63]:
df.loc['林俊翔':'王坤安'] 
df.iloc[-5:-1] 
df.iloc[-5:] 
#df.iloc[0:2]

     chinese  english  math  geo  explore
楊健麟       96       98    89   77       66
柯韋成       51       83    61   70       79
李蓉瑞       79       82    55   82       73
王坤安       64       50    94   94       57
郎慧萍       64       71    54   71       64

In [53]:
df.head()  #可以看前面五筆
df.loc['柯韋成']   #series只有索引沒有欄位
#df.loc['柯韋成']['geo'] = 70
#df

df.loc['柯韋成','geo'] = 70  #如果用loc索引，index後面column，中間可以直接放逗號就好
df
df.head()

     chinese  english  math  geo  explore
魏秋萍       88       97    50   96       75
鄭孟芳       69       98    61   82       83
李彥伸       77       64    76   65       50
李湘婷       88       89    78   60       64
劉佳佩       80       81    65   59       86

In [ ]:
#前十筆
df[:10]

     chinese  english  math  geo  explore
魏秋萍       88       97    50   96       75
鄭孟芳       69       98    61   82       83
李彥伸       77       64    76   65       50
李湘婷       88       89    78   60       64
劉佳佩       80       81    65   59       86
簡國瑋       53       84    54   76       66
童建霖       69       95   100   56       70
陳筱涵       76       83    78  100       98
高智超       68       64    83   70       60
林益妏       72       52    79   80       61

In [ ]:
#倒數十筆
df[-10:]

     chinese  english  math  geo  explore
葉祖雄       61       66    76   86       60
林俊翔       95       69    73   50       63
郭致恬       81       79    98   50       80
盧冠發       53       58    67   56       75
蔡士賢       80       77    51   84       57
楊健麟       96       98    89   77       66
柯韋成       51       83    61   70       79
李蓉瑞       79       82    55   82       73
王坤安       64       50    94   94       57
郎慧萍       64       71    54   71       64

In [ ]:
df['chinese'] + df['english'] + df['math'] + df['geo'] + df['explore']   #陣列運算

魏秋萍    406
鄭孟芳    393
李彥伸    332
李湘婷    379
劉佳佩    371
簡國瑋    333
童建霖    390
陳筱涵    435
高智超    345
林益妏    344
黃柏宇    341
蔡至剛    371
林志成    356
羅幸娥    372
王梅劭    378
吳志宣    424
游倫城    305
周家銘    330
陳淑萍    409
錢佩豪    334
陳信宏    407
林淑安    373
劉慧君    389
林珈發    365
張家秀    375
柯宜臻    385
林瑞喬    398
林麗萍    359
李立偉    338
黃必琪    343
楊偉翔    426
陳奇瑄    380
李進慧    367
王雅琴    384
沈心利    453
鄧哲榮    290
游詩亞    379
蔡欣汝    377
黃靜怡    306
尚偉倫    381
葉祖雄    349
林俊翔    350
郭致恬    388
盧冠發    309
蔡士賢    349
楊健麟    426
柯韋成    344
李蓉瑞    371
王坤安    359
郎慧萍    324
dtype: int64

In [93]:
df.sum(axis=1)    #axis{index (0), columns (1)}
stu_sum = df.sum(axis=1)
stu_mean = stu_sum / 5
stu_mean

魏秋萍    81.2
鄭孟芳    78.6
李彥伸    66.4
李湘婷    75.8
劉佳佩    74.2
簡國瑋    66.6
童建霖    78.0
陳筱涵    87.0
高智超    69.0
林益妏    68.8
黃柏宇    68.2
蔡至剛    74.2
林志成    71.2
羅幸娥    74.4
王梅劭    75.6
吳志宣    84.8
游倫城    61.0
周家銘    66.0
陳淑萍    81.8
錢佩豪    66.8
陳信宏    81.4
林淑安    74.6
劉慧君    77.8
林珈發    73.0
張家秀    75.0
柯宜臻    77.0
林瑞喬    79.6
林麗萍    71.8
李立偉    67.6
黃必琪    68.6
楊偉翔    85.2
陳奇瑄    76.0
李進慧    73.4
王雅琴    76.8
沈心利    90.6
鄧哲榮    58.0
游詩亞    75.8
蔡欣汝    75.4
黃靜怡    61.2
尚偉倫    76.2
葉祖雄    69.8
林俊翔    70.0
郭致恬    77.6
盧冠發    61.8
蔡士賢    69.8
楊健麟    85.2
柯韋成    66.8
李蓉瑞    74.2
王坤安    71.8
郎慧萍    64.8
dtype: float64

###總和、平均

In [94]:
df['total'] = stu_sum
df['average'] = stu_mean

In [95]:
df

     chinese  english  math  geo  explore  total  average
魏秋萍       88       97    50   96       75    406     81.2
鄭孟芳       69       98    61   82       83    393     78.6
李彥伸       77       64    76   65       50    332     66.4
李湘婷       88       89    78   60       64    379     75.8
劉佳佩       80       81    65   59       86    371     74.2
簡國瑋       53       84    54   76       66    333     66.6
童建霖       69       95   100   56       70    390     78.0
陳筱涵       76       83    78  100       98    435     87.0
高智超       68       64    83   70       60    345     69.0
林益妏       72       52    79   80       61    344     68.8
黃柏宇       70       75    81   60       55    341     68.2
蔡至剛       83       69    57   86       76    371     74.2
林志成       57       53    71   93       82    356     71.2
羅幸娥       90       59    95   57       71    372     74.4
王梅劭       73       91    68   50       96    378     75.6
吳志宣       63      100    76   89       96    424     84.8
游倫城       83       56    57   56       53    305     61.0
周家銘       64       97    66   52       51    330     66.0
陳淑萍       98       81    79   68       83    409     81.8
錢佩豪       74       55    64   81       60    334     66.8
陳信宏       70       77    98   79       83    407     81.4
林淑安       88       62    84   68       71    373     74.6
劉慧君       61       88    95   69       76    389     77.8
林珈發       57      100    51   67       90    365     73.0
張家秀       64      100    85   67       59    375     75.0
柯宜臻       68       63    89   96       69    385     77.0
林瑞喬       71      100    61   82       84    398     79.6
林麗萍       81       69    73   80       56    359     71.8
李立偉       77       94    51   53       63    338     67.6
黃必琪       78       68    60   53       84    343     68.6
楊偉翔       73       96    98   94       65    426     85.2
陳奇瑄       96       81    50   67       86    380     76.0
李進慧       74       86    74   57       76    367     73.4
王雅琴       75       55    94   79       81    384     76.8
沈心利       98       94    87   82       92    453     90.6
鄧哲榮       59       55    54   72       50    290     58.0
游詩亞       51       73    91   86       78    379     75.8
蔡欣汝       89       54    80   77       77    377     75.4
黃靜怡       58       61    57   59       71    306     61.2
尚偉倫       92       86    57   76       70    381     76.2
葉祖雄       61       66    76   86       60    349     69.8
林俊翔       95       69    73   50       63    350     70.0
郭致恬       81       79    98   50       80    388     77.6
盧冠發       53       58    67   56       75    309     61.8
蔡士賢       80       77    51   84       57    349     69.8
楊健麟       96       98    89   77       66    426     85.2
柯韋成       51       83    61   60       79    334     66.8
李蓉瑞       79       82    55   82       73    371     74.2
王坤安       64       50    94   94       57    359     71.8
郎慧萍       64       71    54   71       64    324     64.8